[nc]
type = webdav
url = https://nextcloud05.webo.cloud/remote.php/dav/files/451585@gmail.com/
vendor = nextcloud
user = 451585@gmail.com
pass = mG9g6EYar7MX32AxmHiB9g2T7B9H8i--pg

[gvova]
type = drive
client_id = 283619617597-ii2oqsuqast2h0dlfvbp4irtdmrfaj24.apps.googleusercontent.com
client_secret = jlVTpSrUwVg2F8Yuds3Rr5E-
scope = drive
token = {"access_token":"ya29.a0AfH6SMB9OYvFJzJJaJsk1TUSpmgtcFMswXSq0XBuvzXVsvlzWONJMyCmpF6sVsgkYyeY28S417gBqVwZnYDTz8FKU4n0paK1ycl_d9fgunVF0L5Qqui4IzBq4hEI0yz137xJPhz57lgTTMb94GjBXp8NXmsm_w","token_type":"Bearer","refresh_token":"1//0cv2I33lxwvc2CgYIARAAGAwSNwF-L9IrwkeMBpTFi4nRH_iKgngvu-49MJlZT16Gn_GtK1SgBOFZXZmrPHntzyEdGwdfx3KRZ8U","expiry":"2021-06-10T13:33:09.371208038+02:00"}

[gluda]
type = drive
client_id = 283619617597-ii2oqsuqast2h0dlfvbp4irtdmrfaj24.apps.googleusercontent.com
client_secret = jlVTpSrUwVg2F8Yuds3Rr5E-
scope = drive
token = {"access_token":"ya29.a0AfH6SMAcyMFF4LYX5R_euAWMCX4s1MJ0KJZu66kV1XKHlTUABdxqECF_28GO8kTDZ6XZkaRvWrPP8U9daJaW9n4IsD45lYUkI0rvkaxq7zszR7zFHU1RBcgRC5nc91fTmlILyAKDA6B8Mj5p1ULMKi2IGsVljg","token_type":"Bearer","refresh_token":"1//0cFX_W6SYr44yCgYIARAAGAwSNwF-L9Ir3GWJ_7xvyucREXVN61zEmL6i_dtfkFlQzeoQ1ATdYFzp_mSRQL7nmOz7qZgTNR-v8ds","expiry":"2021-06-10T13:33:12.341435522+02:00"}

