[battery]
full_symbol = '🔋'
charging_symbol = '⚡'
discharging_symbol = '↘ '

[[battery.display]]
threshold = 15
style = 'bold red'
discharging_symbol = '📛'

[[battery.display]]
threshold = 30
style = 'bold yellow'
